# Generated by Django 3.0.8 on 2020-07-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('year_2019', models.CharField(max_length=30)),
                ('year_2018', models.CharField(max_length=30)),
                ('year_2017', models.CharField(max_length=30)),
                ('year_2016', models.CharField(max_length=30)),
            ],
        ),
    ]
